name: Admin_Dashboard CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      PORT: ${{ secrets.PORT }}
      VITE_BACKEND_AUTH_SERVICE: ${{ secrets.VITE_BACKEND_AUTH_SERVICE }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage

  # sonarcloud:
  #   runs-on: ubuntu-latest
  #   environment: MY Project Env
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       with:
  #         projectBaseDir: .
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-to-docker:
    name: Build and push Docker Image
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ajay980p/admin_dashboard
      IMAGE_TAG: build-${{ github.run_number }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/prod/Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}